"""Added reply fields for reviews

Revision ID: 27f590ddc4a0
Revises: a1dd4e0bdcdf
Create Date: 2024-12-10 12:32:36.724381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f590ddc4a0'
down_revision = 'a1dd4e0bdcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seller_reply_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('seller_reply_at')
        batch_op.drop_column('seller_reply')

    # ### end Alembic commands ###
