"""added order & order items models

Revision ID: 4cf0569573c9
Revises: 125cbb78e439
Create Date: 2024-12-09 16:59:53.857106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cf0569573c9'
down_revision = '125cbb78e439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.JSON(), nullable=False),
    sa.Column('shipping_method', sa.String(length=50), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('order_uuid')
    )
    op.create_table('order_items',
    sa.Column('item_uuid', sa.String(length=36), nullable=False),
    sa.Column('order_uuid', sa.String(length=36), nullable=False),
    sa.Column('product_uuid', sa.String(length=36), nullable=False),
    sa.Column('variation_uuid', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selected_option', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_uuid'], ['orders.order_uuid'], ),
    sa.ForeignKeyConstraint(['product_uuid'], ['products.product_uuid'], ),
    sa.ForeignKeyConstraint(['variation_uuid'], ['product_variations.variation_uuid'], ),
    sa.PrimaryKeyConstraint('item_uuid')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('card_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_four', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('expiry_month', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('expiry_year', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_holder_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paypal_email', sa.String(length=100), nullable=True))
        batch_op.drop_column('payment_type')
        batch_op.drop_column('payment_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_details', mysql.JSON(), nullable=False))
        batch_op.add_column(sa.Column('payment_type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('paypal_email')
        batch_op.drop_column('card_holder_name')
        batch_op.drop_column('expiry_year')
        batch_op.drop_column('expiry_month')
        batch_op.drop_column('last_four')
        batch_op.drop_column('card_type')
        batch_op.drop_column('type')

    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
