"""add order cancellation fields

Revision ID: 5a8c7df07923
Revises: 4cf0569573c9
Create Date: 2024-12-10 08:43:03.520901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8c7df07923'
down_revision = '4cf0569573c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_at')

    # ### end Alembic commands ###
