"""Added more cancellation fields

Revision ID: a1dd4e0bdcdf
Revises: 5a8c7df07923
Create Date: 2024-12-10 10:36:14.716471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1dd4e0bdcdf'
down_revision = '5a8c7df07923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_rejected_reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('cancellation_rejected_reason')
        batch_op.drop_column('cancellation_rejected_at')
        batch_op.drop_column('cancellation_approved_at')
        batch_op.drop_column('cancellation_requested_at')

    # ### end Alembic commands ###
