"""add banner model and fix wishlist indexes

Revision ID: b22b9d0a275a
Revises: 
Create Date: 2024-12-08 15:01:51.187703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22b9d0a275a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.create_index('idx_banner_order', ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_banners_order'), ['order'], unique=False)

    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index('uq_user_product')
        batch_op.create_index('idx_wishlist_user_product', ['user_uuid', 'product_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index('idx_wishlist_user_product')
        batch_op.create_index('uq_user_product', ['user_uuid', 'product_uuid'], unique=True)

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banners_order'))
        batch_op.drop_index('idx_banner_order')

    # ### end Alembic commands ###
