"""initial migration

Revision ID: b5601782f670
Revises: 
Create Date: 2024-11-18 12:35:24.744238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5601782f670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('verification_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('users',
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('complete_address', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Buyer', 'Seller', 'Admin'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_uuid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('addresses',
    sa.Column('address_uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('address_name', sa.String(length=100), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('complete_address', sa.String(length=255), nullable=False),
    sa.Column('additional_info', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default_shipping', sa.Boolean(), nullable=True),
    sa.Column('is_default_billing', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('address_uuid')
    )
    op.create_table('admin_info',
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('admin_email', sa.String(length=120), nullable=False),
    sa.Column('admin_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    op.create_table('payment_methods',
    sa.Column('payment_uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('payment_details', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('payment_uuid')
    )
    op.create_table('seller_info',
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('business_owner', sa.String(length=100), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('business_email', sa.String(length=120), nullable=False),
    sa.Column('business_phone', sa.String(length=20), nullable=False),
    sa.Column('business_country', sa.String(length=50), nullable=False),
    sa.Column('business_province', sa.String(length=50), nullable=False),
    sa.Column('business_city', sa.String(length=50), nullable=False),
    sa.Column('business_address', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=False),
    sa.Column('tax_certificate_doc', sa.String(length=200), nullable=False),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', 'Suspended', name='seller_status'), nullable=True),
    sa.Column('violation_type', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_uuid'], ),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_table('shops',
    sa.Column('shop_uuid', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_country', sa.String(length=100), nullable=False),
    sa.Column('business_province', sa.String(length=100), nullable=False),
    sa.Column('business_city', sa.String(length=100), nullable=False),
    sa.Column('business_address', sa.String(length=255), nullable=False),
    sa.Column('shop_logo', sa.String(length=255), nullable=True),
    sa.Column('total_products', sa.Integer(), nullable=True),
    sa.Column('shop_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_info.seller_id'], ),
    sa.PrimaryKeyConstraint('shop_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shops')
    op.drop_table('seller_info')
    op.drop_table('payment_methods')
    op.drop_table('admin_info')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('phone_verifications')
    op.drop_table('otp')
    # ### end Alembic commands ###
